resources:
  - repo: self

trigger:
  batch: true

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(registryConnection)'
              repository: '$(repository)'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              arguments: '--build-arg revision=$(Build.BuildNumber) --build-arg storageContainerName=$(storageContainerName) --build-arg serverName=$(serverName) --build-arg sentryDsn=$(sentryDsn)'
              tags: |
                $(Build.BuildNumber)
                latest
          - task: Docker@2
            inputs:
              containerRegistry: '$(registryConnection)'
              repository: '$(repository)'
              command: 'push'
              tags: |
                $(Build.BuildNumber)
                latest
