gongyu:
  version: "@revision@"
  storageContainerName: @gongyu.storageContainerName@
  maxFileDownloadSize: 15728640

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  output:
    ansi:
      enabled: always
server:
  tomcat:
    max-http-post-size: 15MB