gongyu:
  version: "@revision@"
  storageContainerName: @gongyu.storageContainerName@
  maxFileDownloadSize: 52428800

azure:
  keyvault:
    uri: https://${KEYVAULT_NAME}.vault.azure.net/
    client-id: ${KEYVAULT_CLIENT_ID}
    client-key: ${KEYVAULT_CLIENT_SECRET}
    token-acquire-timeout-seconds: 15

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
