gongyu:
  dropboxAccessKey: @gongyu.dropboxAccessKey@
  storageConnectionString: @gongyu.storageConnectionString@
  storageContainerName: @gongyu.storageContainerName@
  maxFileDownloadSize: 52428800

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
